/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "node-1--K66CuB-C5c3Hje6rgDfy0FsmcUtrN3yMukgnmmYdFTtbtxbnSESIRNfJylvp-t2W4NDthKNEhQ1bmfDkqZph-yGpRMp3eIC-zCH1rUfbYglqeo9L70QR8B1",
  "tt": "tt-1-CGDNoZk8zBn2N-nZB8vhHKtULyVFPAOybb8t6p6tWf8=",
  "version": "2020-11-20"
}

export default ebconfig;